export type CalculatorCategory =
  | "financial"
  | "work"
  | "lifestyle"
  | "health"
  | "dev";

export const CATEGORY_LABELS: Record<CalculatorCategory, string> = {
  financial: "금융 · 재테크",
  work: "직장 · 노무",
  lifestyle: "일상 · 생활",
  health: "건강 · 운동",
  dev: "개발 · IT",
};

export interface CalculatorMeta {
  /** URL 경로 (예: /age) */
  slug: string;
  /** 카드/헤더 제목 */
  title: string;
  /** 짧은 설명 */
  description: string;
  /** 검색용 키워드 (한/영) */
  keywords: string[];
  /** 카드 이모지 아이콘 */
  emoji: string;
  /** 카드 강조 색 (tailwind gradient from-to) */
  accent: string;
  /** SEO용 상세 설명 */
  seo: string;
  /** 카테고리 분류 */
  category: CalculatorCategory;
}

export const calculators: CalculatorMeta[] = [
  {
    slug: "/savings-interest",
    title: "예적금 이자 계산기",
    description: "단리·복리, 일반과세·세금우대·비과세를 반영한 실제 수령액 계산",
    keywords: [
      "예금",
      "적금",
      "이자계산",
      "단리",
      "복리",
      "세금우대",
      "비과세",
      "이자소득세",
      "savings",
    ],
    emoji: "💰",
    accent: "from-yellow-500/15 to-amber-500/10",
    seo: "예금(거치식)과 적금(적립식)의 단리·복리 이자를 계산하고, 일반과세(15.4%)·세금우대(9.5%)·비과세 혜택을 반영한 실제 세후 수령액을 확인할 수 있습니다.",
    category: "financial",
  },
  {
    slug: "/loan-repayment",
    title: "대출 상환 계산기",
    description: "원리금균등·원금균등·만기일시 상환 방식별 월 상환액과 총이자 비교",
    keywords: [
      "대출",
      "이자계산",
      "원리금균등",
      "원금균등",
      "만기일시상환",
      "상환스케줄",
      "loan",
      "월상환액",
    ],
    emoji: "🏦",
    accent: "from-blue-500/15 to-cyan-500/10",
    seo: "대출 원금, 연이자율, 대출기간을 입력하면 원리금균등·원금균등·만기일시상환 방식별 월 상환액, 총 이자, 연차별 상환 스케줄을 비교할 수 있습니다.",
    category: "financial",
  },
  {
    slug: "/stock-average",
    title: "주식 평단가(물타기) 계산기",
    description: "보유 수량·평단가에 추가 매수를 더해 최종 평단가와 총 투자금액 계산",
    keywords: [
      "주식",
      "평단가",
      "물타기",
      "평균단가",
      "추가매수",
      "stock",
      "average price",
    ],
    emoji: "📈",
    accent: "from-red-500/15 to-rose-500/10",
    seo: "현재 보유 수량과 평단가에 추가 매수 수량·가격을 더해 최종 평균단가, 총 보유수량, 총 투자금액을 즉시 계산합니다.",
    category: "financial",
  },
  {
    slug: "/salary",
    title: "연봉 실수령액 계산기",
    description: "2026년 기준 4대보험과 근로소득세를 제외한 예상 월 실수령액 계산",
    keywords: [
      "연봉",
      "실수령액",
      "4대보험",
      "국민연금",
      "건강보험",
      "고용보험",
      "근로소득세",
      "월급",
      "salary",
    ],
    emoji: "💵",
    accent: "from-green-500/15 to-emerald-500/10",
    seo: "연봉과 부양가족 수를 입력하면 2026년 기준 국민연금·건강보험·장기요양보험·고용보험·근로소득세·지방소득세를 제외한 예상 월 실수령액과 1억 5천만원까지의 연봉별 실수령액 참고표를 계산합니다.",
    category: "work",
  },
  {
    slug: "/severance-pay",
    title: "퇴직금 계산기",
    description: "입사일·퇴사일과 3개월 평균임금으로 예상 퇴직금을 계산",
    keywords: [
      "퇴직금",
      "퇴직금계산",
      "평균임금",
      "퇴직급여",
      "근속연수",
      "재직일수",
      "severance",
    ],
    emoji: "💼",
    accent: "from-purple-500/15 to-indigo-500/10",
    seo: "입사일과 퇴사일, 퇴직 전 3개월 월평균 임금, 연간 상여금, 연차수당을 입력하면 고용노동부 산정 방식(1일 평균임금 × 30일 × 재직일수/365)에 따른 예상 퇴직금을 계산합니다.",
    category: "work",
  },
  {
    slug: "/unemployment-benefit",
    title: "실업급여 계산기",
    description: "나이·고용보험 가입기간·평균임금으로 구직급여 일액과 총 수령액 계산",
    keywords: [
      "실업급여",
      "구직급여",
      "고용보험",
      "소정급여일수",
      "실업급여계산",
      "상한액",
      "하한액",
      "unemployment",
    ],
    emoji: "🛟",
    accent: "from-sky-500/15 to-blue-500/10",
    seo: "퇴사 시 만 나이, 고용보험 가입기간, 퇴직 전 3개월 월평균 임금을 입력하면 구직급여(실업급여) 1일 지급액과 소정급여일수, 총 예상 수령액을 계산합니다. 상한액·하한액 기준을 자동 반영합니다.",
    category: "work",
  },
  {
    slug: "/weekly-holiday-pay",
    title: "주휴수당 계산기",
    description: "시급과 주 근로시간으로 주휴수당·주급·월 예상급여 계산 (알바 필수)",
    keywords: [
      "주휴수당",
      "주휴수당계산",
      "알바",
      "아르바이트",
      "시급",
      "최저임금",
      "주급",
      "월급환산",
    ],
    emoji: "⏰",
    accent: "from-rose-500/15 to-orange-500/10",
    seo: "시급과 1주 소정근로시간을 입력하면 주휴수당 지급 조건(주 15시간 이상) 충족 여부와 주휴수당, 주휴수당을 포함한 주급·월 예상급여를 2026년 최저임금 기준으로 계산합니다.",
    category: "work",
  },
  {
    slug: "/annual-leave",
    title: "연차 계산기",
    description: "입사일 기준 발생 연차 개수와 미사용 연차수당을 한 번에 계산",
    keywords: [
      "연차",
      "연차계산",
      "연차개수",
      "연차수당",
      "유급휴가",
      "미사용연차",
      "통상임금",
      "annual leave",
    ],
    emoji: "🌴",
    accent: "from-teal-500/15 to-emerald-500/10",
    seo: "입사일과 기준일을 입력하면 근로기준법에 따른 발생 연차 개수(1년 미만 월 단위 연차 포함, 최대 25일)를 계산하고, 월 통상임금 기준 미사용 연차수당까지 함께 확인할 수 있습니다.",
    category: "work",
  },
  {
    slug: "/dutch-pay",
    title: "더치페이(N분의 1) 계산기",
    description: "1차/2차 정산, 특정인 제외, 100원·1000원 단위 절사까지 지원",
    keywords: [
      "더치페이",
      "n분의1",
      "1/n",
      "정산",
      "회식비",
      "1차",
      "2차",
      "절사",
      "dutch pay",
      "split bill",
    ],
    emoji: "🧾",
    accent: "from-orange-500/15 to-red-500/10",
    seo: "회식비, 여행 경비 등을 1차·2차 등 차수별로 나누어 정산하고, 특정 인원 제외와 100원·1000원 단위 절사까지 지원하는 더치페이 계산기입니다.",
    category: "lifestyle",
  },
  {
    slug: "/age",
    title: "만 나이 계산기",
    description: "생년월일로 만 나이·연 나이·띠·다음 생일까지 남은 날을 계산",
    keywords: ["만나이", "나이계산", "연나이", "띠", "age", "생일", "birthday"],
    emoji: "🎂",
    accent: "from-pink-500/15 to-rose-500/10",
    seo: "생년월일과 기준일을 입력하면 만 나이, 연 나이, 띠, 다음 생일까지 남은 일수를 즉시 계산합니다. 2023년 시행된 만 나이 통일법 기준으로 정확하게 산정합니다.",
    category: "lifestyle",
  },
  {
    slug: "/dday",
    title: "디데이(D-Day) 계산기",
    description: "목표일까지 남은 날, 특정일로부터 지난 날·기념일(100일·1주년)을 계산",
    keywords: [
      "디데이",
      "dday",
      "d-day",
      "날짜계산",
      "기념일",
      "100일",
      "며칠",
      "날짜세기",
      "countdown",
    ],
    emoji: "📅",
    accent: "from-violet-500/15 to-purple-500/10",
    seo: "목표 날짜까지 남은 D-Day, 특정 시작일로부터 오늘까지 지난 일수, 100일·200일·1주년 등 주요 기념일 날짜를 한 번에 계산합니다.",
    category: "lifestyle",
  },
  {
    slug: "/real-estate-tax",
    title: "부동산 취득세 계산기",
    description: "주택 수·취득가액·조정지역 여부로 취득세·교육세·농특세 자동 계산",
    keywords: [
      "부동산",
      "취득세",
      "지방교육세",
      "농어촌특별세",
      "주택세금",
      "real estate",
      "tax",
    ],
    emoji: "🏠",
    accent: "from-emerald-500/15 to-teal-500/10",
    seo: "주택 보유 수, 취득가액, 조정대상지역 여부, 전용면적을 입력하면 취득세, 지방교육세, 농어촌특별세를 자동으로 계산하고 요율표를 함께 제공합니다.",
    category: "financial",
  },
  {
    slug: "/traffic-fine",
    title: "교통 범칙금·과태료 계산기",
    description: "위반 항목·차종·보호구역 여부로 범칙금/과태료와 벌점을 조회",
    keywords: [
      "과태료",
      "범칙금",
      "벌점",
      "과속",
      "신호위반",
      "교통위반",
      "어린이보호구역",
      "traffic",
      "fine",
    ],
    emoji: "🚗",
    accent: "from-amber-500/15 to-orange-500/10",
    seo: "과속, 신호위반 등 위반 항목과 차종, 보호구역 여부를 선택하면 범칙금·과태료 금액과 벌점을 한눈에 확인할 수 있습니다.",
    category: "lifestyle",
  },
  {
    slug: "/ev-charging",
    title: "전기차 충전요금 계산기",
    description: "배터리 용량·충전량·충전기 종류로 예상 충전 시간과 비용 계산",
    keywords: [
      "전기차",
      "충전요금",
      "충전비용",
      "급속충전",
      "완속충전",
      "EV",
      "charging",
      "배터리",
    ],
    emoji: "🔋",
    accent: "from-sky-500/15 to-indigo-500/10",
    seo: "전기차 배터리 용량, 현재 잔량, 목표 충전량, 충전기 종류와 계절·시간대를 선택하면 예상 충전 시간과 충전 비용을 계산합니다.",
    category: "lifestyle",
  },
  {
    slug: "/electricity-bill",
    title: "전기요금 계산기",
    description: "월 사용량(kWh)으로 누진 구간별 주택용 전기요금을 계산",
    keywords: [
      "전기요금",
      "전기세",
      "누진세",
      "누진구간",
      "한전",
      "주택용전기",
      "전기요금계산",
      "kWh",
      "에어컨 전기세",
    ],
    emoji: "⚡",
    accent: "from-yellow-500/15 to-orange-500/10",
    seo: "월 전기 사용량(kWh)과 계절, 주택용 저압·고압을 선택하면 누진 구간별 전력량요금, 기본요금, 기후환경요금, 부가가치세, 전력산업기반기금까지 반영한 예상 전기요금을 계산합니다. 여름철 에어컨 사용량 요금 확인에 유용합니다.",
    category: "lifestyle",
  },
  {
    slug: "/unit-converter",
    title: "단위 변환기",
    description: "길이·넓이·무게·부피·데이터 크기를 한 번에 상호 변환",
    keywords: [
      "단위변환",
      "길이변환",
      "넓이변환",
      "무게변환",
      "부피변환",
      "평수변환",
      "cm",
      "inch",
      "kg",
      "lb",
      "GB",
      "unit converter",
    ],
    emoji: "📐",
    accent: "from-cyan-500/15 to-blue-500/10",
    seo: "길이(cm·inch), 넓이(평·㎡), 무게(kg·lb), 부피(L·갤런), 데이터 크기(GB·TB) 등 단위를 입력 즉시 모든 단위로 한 번에 변환해 보여줍니다.",
    category: "lifestyle",
  },
  {
    slug: "/bmi-bmr",
    title: "BMI·기초대사량 계산기",
    description: "키·몸무게·나이·활동량으로 BMI, 비만도, 기초대사량, 권장 칼로리 계산",
    keywords: [
      "BMI",
      "체질량지수",
      "기초대사량",
      "BMR",
      "TDEE",
      "비만도",
      "표준체중",
      "권장칼로리",
      "다이어트",
    ],
    emoji: "⚖️",
    accent: "from-lime-500/15 to-green-500/10",
    seo: "키, 몸무게, 나이, 성별, 활동량을 입력하면 BMI(체질량지수), 비만도 판정, 표준체중, 기초대사량(BMR), 일일 권장 칼로리(TDEE)를 계산합니다.",
    category: "health",
  },
  {
    slug: "/one-rep-max",
    title: "1RM(웨이트 트레이닝) 계산기",
    description: "사용 중량·반복 횟수로 1회 최대 중량(1RM)과 %1RM 훈련 강도표 계산",
    keywords: [
      "1RM",
      "원렙맥스",
      "웨이트트레이닝",
      "헬스",
      "벤치프레스",
      "스쿼트",
      "데드리프트",
      "최대중량",
      "one rep max",
    ],
    emoji: "🏋️",
    accent: "from-slate-500/15 to-zinc-500/10",
    seo: "특정 무게로 반복한 횟수를 입력하면 Epley·Brzycki·Lombardi 공식으로 1RM(1회 최대 중량)을 추정하고, 훈련 강도별(%1RM) 목표 중량표를 제공합니다.",
    category: "health",
  },
  {
    slug: "/base-converter",
    title: "진법 변환·바이트 계산기",
    description: "2진수·8진수·10진수·16진수 상호 변환 및 필요 비트·바이트 수 계산",
    keywords: [
      "진법변환",
      "2진수",
      "8진수",
      "16진수",
      "10진수",
      "바이트",
      "비트",
      "binary",
      "hex",
      "converter",
    ],
    emoji: "🔢",
    accent: "from-indigo-500/15 to-violet-500/10",
    seo: "2진수, 8진수, 10진수, 16진수 값을 입력하면 나머지 진법으로 즉시 변환하고, 값을 표현하는 데 필요한 비트·바이트 수를 계산합니다.",
    category: "dev",
  },
  {
    slug: "/color-converter",
    title: "RGB ↔ HEX 색상 변환기",
    description: "HEX·RGB 색상 코드를 상호 변환하고 색상을 미리보기",
    keywords: [
      "색상변환",
      "RGB",
      "HEX",
      "컬러코드",
      "컬러피커",
      "웹디자인",
      "color picker",
      "color converter",
    ],
    emoji: "🎨",
    accent: "from-fuchsia-500/15 to-pink-500/10",
    seo: "HEX 코드와 RGB 값을 실시간으로 상호 변환하고 색상 미리보기, CSS rgb() 문자열까지 함께 확인할 수 있는 색상 변환기입니다.",
    category: "dev",
  },
  {
    slug: "/unix-timestamp",
    title: "Unix Timestamp 변환기",
    description: "유닉스 타임스탬프와 날짜·시간을 양방향으로 변환",
    keywords: [
      "유닉스타임스탬프",
      "unix timestamp",
      "epoch",
      "타임스탬프변환",
      "날짜변환",
      "ISO8601",
    ],
    emoji: "⏱️",
    accent: "from-teal-500/15 to-cyan-500/10",
    seo: "Unix Timestamp(초·밀리초)를 날짜/시간으로, 날짜/시간을 Unix Timestamp로 양방향 변환하며 ISO 8601(UTC) 형식도 함께 제공합니다.",
    category: "dev",
  },
];

export function getCalculator(slug: string): CalculatorMeta | undefined {
  return calculators.find((c) => c.slug === slug);
}
